# Generated by Django 4.1 on 2023-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartUserprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'chart_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T2',
            fields=[
                ('t2_id', models.AutoField(primary_key=True, serialize=False)),
                ('t2_type', models.CharField(max_length=40)),
                ('t2_date', models.DateTimeField()),
            ],
            options={
                'db_table': 't2',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
